In [ ]:
#TASK 1

numbers = open("Numbers.txt", "w")

no1 = int(input("Enter your 1st number"))
no2 = int(input("Enter your 2nd number"))
no3 = int(input("Enter your 3rd number"))
no4 = int(input("Enter your 4th number"))


numbers.write(str(no1))
numbers.write("\n")
numbers.write(str(no2))
numbers.write("\n")
numbers.write(str(no3))
numbers.write("\n")
numbers.write(str(no4))
numbers.close()

with open ("Numbers.txt","r") as numbers:
        data = numbers.read().replace('\n',',')
numbers.close()

print(data)



In [ ]:
#TASK 2
def grade():

    percent = int(input("what was your percentage mark?"))

    if 100 >= percent >= 80:
        mark_grade = "A"
    elif 80 > percent >= 70:
        mark_grade = "B"
    elif 70 > percent >= 60:
        mark_grade ="C"
    elif 60 > percent >= 50:
        mark_grade ="D"
    elif 50 > percent >= 0:
        mark_grade ="U"
    else:
        mark_grade ="please enter a number between 0 - 100"


    output = "Your percentage mark of " + str(percent) + "% gives you a grade of " + mark_grade

    return output


In [ ]:
message = grade()
print(message)


In [238]:
#TASK 2 Extension
def compare():

    percent = int(input("what was your percentage mark?"))
    target = input("What is your target grade? (A - U)")

    if 100 >= percent >= 80:
        mark_grade = "A"
        if target == mark_grade:
            print("Congratulations you've hit your target!")
        elif target >= mark_grade:
            print("Congratulations you've exceeded your target!")
        elif target < mark_grade:
            print("Unfortunately you've missed your target")
        else:
            print("Please enter a grade between A* and U in capitals")
    elif 80 > percent >= 70:
        mark_grade = "B"
        if target == mark_grade:
            print("Congratulations you've hit your target!")
        elif target >= mark_grade:
            print("Congratulations you've exceeded your target!")
        elif target < mark_grade:
            print("Unfortunately you've missed your target")
        else:
            print("Please enter a grade between A* and U in capitals")
    elif 70 > percent >= 60:
        mark_grade ="C"
        if target == mark_grade:
            print("Congratulations you've hit your target!")
        elif target >= mark_grade:
            print("Congratulations you've exceeded your target!")
        elif target < mark_grade:
            print("Unfortunately you've missed your target")
        else:
            print("Please enter a grade between A* and U in capitals")
    elif 60 > percent >= 50:
        mark_grade ="D"
        if target == mark_grade:
            print("Congratulations you've hit your target!")
        elif target >= mark_grade:
            print("Congratulations you've exceeded your target!")
        elif target < mark_grade:
            print("Unfortunately you've missed your target")
        else:
            print("Please enter a grade between A* and U in capitals")
    elif 50 > percent >= 0:
        mark_grade ="U"
        if target == mark_grade:
            print("Congratulations you've hit your target!")
        elif target >= mark_grade:
            print("Congratulations you've exceeded your target!")
        elif target < mark_grade:
            print("Unfortunately you've missed your target")
        else:
            print("Please enter a grade between A* and U in capitals")
    else:
        mark_grade ="please enter a number between 0 - 100"

    

    output = "Your percentage mark of " + str(percent) + "% gives you a grade of " + mark_grade + " and you target was "+ target

    return output

In [239]:
message2 = compare()
print(message2)

Congratulations you've exceeded your target!
Your percentage mark of 89% gives you a grade of A and you target was B


In [241]:
#NUMPY TASKS
#1

import numpy as np

array = np.arange(10)

print(array)

[0 1 2 3 4 5 6 7 8 9]


In [243]:
#2
import numpy as np
array = np.array([True, True, True, True, True, True, True, True, True])

newArray = array .reshape (3,3)
print(newArray)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [245]:
#3
import numpy as np

array = np.arange(11)

print(array)

array2 = np.arange(1, 10, 2)
print(array2)



[ 0  1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [249]:
#4
import numpy as np

array = np.arange(11)
array[array%2 == 1] = -1 

print(array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


In [251]:
#5
import numpy as np

array = np.arange(10)

array2 = array.reshape(2,5)

print(array2)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [260]:
#6

import numpy as np

a = np.arange (1,10)
b = np.arange (11,20)
c = np.dot(a,b)
sum = np.sum (c)
print(c)
print(sum)

735
